matrix:
  include:
    - language: node_js
      - "node"
      cache:
        directories:
          - client/node_modules
      script:
        - cd client
        - npm i
        - npm test
    - language: go
      go:
        - 1.x
        - "1.10"
        - 1.11.x
        - master